/**
 * Training Engines barrel export
 */

export {
  SchulteEngine,
  generateGrid,
  createInitialState,
  validateGrid,
  getDifficultyFromGridSize,
  type GridSize,
  type SchulteConfig,
  type SchulteState,
  type SchulteResult,
  type TapRecord,
} from './schulte';

export {
  StroopEngine,
  generateTrials,
  generateTrial,
  createInitialState as createStroopInitialState,
  validateTrial,
  validateTrials,
  getConfigFromDifficulty as getStroopConfigFromDifficulty,
  CHINESE_COLORS,
  COLOR_MAP,
  COLOR_NAME_MAP,
  type ChineseColor,
  type StroopConfig,
  type StroopState,
  type StroopTrial,
  type StroopResponse,
  type StroopResult,
} from './stroop';

export {
  SequenceEngine,
  generateSequence,
  createSequenceInitialState,
  detectNBackMatch,
  adjustDifficulty,
  getSequenceConfigFromDifficulty,
  validateSequence,
  validateStimulus,
  getStimuliForType,
  NUMBER_STIMULI,
  LETTER_STIMULI,
  POSITION_STIMULI,
  type StimulusType,
  type SequenceConfig,
  type SequenceState,
  type SequenceItem,
  type SequenceResponse,
  type SequenceResult,
} from './sequence';

export {
  AuditoryEngine,
  generateAuditoryTrials,
  generateAuditoryTrial,
  createAuditoryInitialState,
  getAuditoryConfigFromDifficulty,
  validateAuditoryTrial,
  validateAuditoryTrials,
  recordResponse,
  calculateAuditoryStats,
  CHINESE_SOUNDS,
  SOUND_MAP,
  type ChineseSound,
  type AuditoryConfig,
  type AuditoryState,
  type AuditoryTrial,
  type AuditoryResponse,
  type AuditoryResult,
} from './auditory';

export {
  BilateralEngine,
  generatePatterns,
  generatePattern,
  createBilateralInitialState,
  getBilateralConfigFromDifficulty,
  adjustBilateralDifficulty,
  validatePattern,
  validatePatterns,
  validateMirrorPattern,
  calculateMirrorCoordinate,
  checkResponse,
  recordResponse as recordBilateralResponse,
  type BilateralConfig,
  type BilateralState,
  type BilateralPattern,
  type BilateralTarget,
  type BilateralResponse,
  type BilateralResult,
} from './bilateral';

export {
  ClassificationEngine,
  generateItem,
  generateItems,
  generateRule,
  generateDifferentRule,
  createInitialState as createClassificationInitialState,
  getConfigFromDifficulty as getClassificationConfigFromDifficulty,
  getAttributeCountFromDifficulty,
  validateItem,
  validateRule,
  validateRuleDeterminism,
  getShapeName,
  getColorName,
  getSizeName,
  SHAPES,
  COLORS,
  SIZES,
  ATTRIBUTE_TYPES,
  type Shape,
  type Color,
  type Size,
  type AttributeType,
  type ClassificationItem,
  type ClassificationRule,
  type ClassificationConfig,
  type ClassificationState,
  type ClassificationResponse,
  type ClassificationResult,
} from './classification';

export {
  SceneEngine,
  generateScene,
  generateElement,
  generateTestQuestions,
  createSceneInitialState,
  getSceneConfigFromDifficulty,
  adjustSceneDifficulty,
  validateElement,
  validateScene,
  validateTestQuestion,
  validateTestQuestions,
  getPositionDescription,
  ELEMENT_TYPES,
  ELEMENT_NAME_MAP,
  type ElementType,
  type TestType,
  type SceneElement,
  type SceneTestQuestion,
  type QuestionType,
  type SceneConfig,
  type SceneState,
  type ScenePhase,
  type SceneResponse,
  type SceneResult,
} from './scene';
